main: com.foundrysoftware.minecraft.plugins.PluginTemplate
name: PluginTemplate
version: 1.0-SNAPSHOT

commands:
  simple:
    description: Nothing yet
  hawkeye:
    description: /hawkeye [Potion_Type]
